import torch

x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
exp_x = torch.exp(x)
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
cat_0 = torch.cat((X, Y), dim=0)
cat_1 = torch.cat((X, Y), dim=1)
print(x + y)
print(x - y)
print(x * y)
print(x ** y)
print(exp_x)
print(cat_0)
print(cat_1)
print(X == Y)
print(X.sum())
